### ISSUE TITLE
what is mysql socket path ?

### ISSUE THREAD

**Issue by changchichung** [alexhorn/docker-piler#1]
I use your example docker-compose.yml to start containers , then run make install and make postinstall.
about what is mysql hostname ? maybe localhost is just safe .
but the next question , what is mysql socket path ,I have no idea what it is ?

**Comment by alexhorn** [comment]
If you use the example the MySQL hostname is `piler-db`. You can ignore the MySQL socket path setting.

**Comment by changchichung** [comment]
piler-db is ok .
and , no , I cant just ignoe , if I type nothing , the script wont accept.
